language: go

go:
  - 1.6

before_install:
  - mkdir -p $HOME/gopath/src/sourcegraph.com/sourcegraph
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/sourcegraph.com/sourcegraph/rwvfs
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/sourcegraph.com/sourcegraph/rwvfs
  - cd $TRAVIS_BUILD_DIR

install:
  - go get golang.org/x/tools/cmd/vet

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d ./)
  - go tool vet -composites=false ./
  - go test -v -race ./...
